name: quizal
description: A Testing Project for Join Member.id as Mobile Developer

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.6
  sizer: ^2.0.15
  package_info_plus: ^4.0.1
  freezed_annotation: ^2.2.0
  shimmer: ^2.0.0
  firebase_core: ^2.13.0
  firebase_database: ^10.2.1
  share_plus: ^7.0.2
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  flutter_gen_runner: ^5.3.1
  json_serializable: ^6.7.0
  freezed: ^2.3.4
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"

flutter_gen:
  output: lib/utils/resources/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/
